### ISSUE TITLE
Solve our requires.io problem.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#561] opened 2017-04-21 15:07 UTC
Recently Hypothesis elected to ship new patch releases for each PR that gets merged to master using an automated process (see HypothesisWorks/hypothesis-python#555). This is not inherently a problem. However, our use of requires.io means that each minor release of any of our test dependencies will cause the opening of a number of pull requests: for Hypothesis, that number currently stands at 11 and will only advance over time as we make further releases.

Each of these PRs takes a certain amount of manual effort to actually merge, but more importantly triggers a number of builds that clog up the Travis queue. This was not a problem when each of these requires.io builds was intermittent (SMALL_INT number a week), but with Hypothesis' new accelerated release schedule we are likely to see a dramatic increase in the number of these builds we have to handle. This will increase the load on my already frankly quite constricted Travis-CI queue, and will also take an increased amount of manual effort to verify.

The ideal solution would be to rate-limit these PRs so that they're batched up to run about once a week. This would keep most of the benefit of this process, without leading to a higher-than-ideal workload. However, requires.io does not appear to support any rate limiting of this kind. pyup.io, a competing service, *does* offer that functionality but *does not* support running against multiple branches at once, functionality currently used heavily by hyper-h2.

This puts us in a bit of a bind. We need to do at least one of the following:

- Remove the pin on test dependencies. This is a bad idea: random-ass updates of the test dependencies can cause failures that are only encountered by end-users or by contributors making feature changes, and these become hard to debug and not well surfaced. We have the pins and auto-PRs for a reason!
- Widen the pin on Hypothesis. As Hypothesis is the project that has moved to a faster build schedule, we can neatly resolve this issue by pinning to *minor* releases of Hypothesis rather than patch releases. This does improve the situation, but patch releases of projects are still very useful and it'd be good to be somewhat current if we can be.
- Get requires.io improved to allow us to batch the PRs.
- Get pyup.io fixed to allow us to work with multiple branches and migrate to pyup.io.
- Take the [logic that pyup.io uses](https://github.com/pyupio/pyup) and run our own server that just runs batch jobs against each branch (or run that using my own laptop). This is a pretty inferior option because it relies on us having our own infrastructure (gross), but does allow us to retrofit the "pick all the branches" option onto pyup's feature set.
- Just ignore the requires.io PRs until once a week? That will have the affect of batching them, I think, while letting them sit there and be an annoyance, but maybe we can just pretend they don't exist most of the time.
- Something else, I dunno?

It'd be interesting to see what thoughts contributors have about this. We may also want to submit a feature request to pyup, as [they clearly have the ability to work with arbitrary branches](https://pyup.io/docs/configuration/#changing-the-branch): they just don't let you choose more than one at once!

**Comment by alexwlchan** [comment] 2017-04-21 15:10
Admittedly I haven’t tried to set it up, but it sounds from the homepage like requires.io offers this, and poking the site a little suggests I can batch updates?

<img width="938" alt="screen shot 2017-04-21 at 16 10 13" src="https://cloud.githubusercontent.com/assets/301220/25283832/0712bf2e-26ad-11e7-8134-1601cc922abc.png">

I’m not sure what your setup looks like though.

**Comment by Lukasa** [comment] 2017-04-21 15:12
Hrm, that seems like an extremely non-obvious way to flag that feature. What combination of flags am I supposed to use here? Outdated == Never plus Digest == Weekly?

**Comment by Lukasa** [comment] 2017-04-21 15:14
I kinda read that "digest" as being about sending an *email* digest and just assumed it did nothing for PRs.

**Comment by alexwlchan** [comment] 2017-06-18 19:48
So although #562 solves this problem for pull requests opened manually, it didn’t make as much difference to requires.io builds as we might have initially hoped. Travis reads the config from the branch it’s building, not from master. This means that requires.io PRs are still triggering two builds per patch.

I’ve backported 78a45dc to our release branches and will open a series of PRs shortly – once merged, this should roughly halve the pressure on our Travis queues when we get a dependency bump.

**Comment by alexwlchan** [comment] 2017-09-03 21:36
I’ve just cleared the requires.io backlog (again).

I think we should reconsider widening the Hypothesis pin to minor releases, or dropping it entirely.

The Hypothesis release cycle is, if anything, getting faster. In the last fortnight alone:

* 15 releases
* 10 patch releases
* No feature changes I can see that would be of interest to h2
* No CI failures caused by the new release

And David is about to start PhD work on Hypothesis, so I’d expect changes will speed up, not slow down. By the time we’re closing these PRs, we end up rolling several releases into one, anyway.

Although failures caused by shifting test dependencies is annoying, the small-but-frequent versions of Hypothesis allow an easy bisection process to identify problematic versions (if any), and we’re weighing the _potential_ frustration of that _hypothetical_ problem against the _actual_ hassle and busywork caused by these PRs right now.

**Comment by Lukasa** [comment] 2017-09-04 05:57
Yeah, that sounds reasonable. Want to open a PR for it?

**Closed** 2020-02-08 14:54 UTC
